namespaceOverride: "re-advisor"
ollamaUrls: ["http://re-advisor-ollama:11434"]
pipelines:
  enabled: false
tika:
  enabled: false
websocket:
  enabled: true
manager: redis
persistence:
  enabled: true
  size: 50Gi
  storageClass: "local-storage"
  selector: {"matchLabels": {"app.kubernetes.io/instance": "re-advisor", "storage.role": "data-store"}}
# -- Env vars added to the Open WebUI deployment. Most up-to-date environment variables can be found here: https://docs.openwebui.com/getting-started/env-configuration. Variables can be defined as list or map style.
extraEnvVars:
  - name: WEBUI_URL
    value: "https://re-advisor.ui.stark.labs"
  - name: ENABLE_PERSISTENT_CONFIG
    value: "False"
  - name: ENABLE_USAGE_POOL_CLEANUP
    value: "False"
