apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: lab-gateway
  namespace: nginx-gateway
spec:
  gatewayClassName: nginx
  listeners:
  - name: lab-http-ingress
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All # This allows HTTPRoutes in other namespaces to attach to this Gateway
